language: php

services:
  - mysql

addons:
  apt:
    sources:
    - mysql-5.7-trusty
    packages:
    - mysql-server

php:
  - 7.2

sudo: required

before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade
  - sudo service mysql restart
  - mysql -e 'CREATE DATABASE IF NOT EXISTS travis_test;'

install: composer install

before_script:
  - cp .env.travis .env
  - npm install
  - php artisan migrate
  - php artisan db:seed
  - php artisan import:prevair
  - php artisan import:gas
  - php artisan import:silex
  - php artisan import:ter

script:
  - travis_retry vendor/bin/phpunit

jobs:
  include:
    - stage: PHP Lint
      env: php -l
      install: travis_retry composer install
      script:
        - if find . -type f -name "*.php" ! -path "./vendor/*" | xargs -n 1 -P 8 -I % php -d error_reporting=32767 -l % \; 2>&1 >&- | grep "^" ; then exit 1; fi
    - stage: PHP CS Fixer
      env: php-cs-fixer
      install:
        - phpenv config-rm xdebug.ini
        - travis_retry composer install
      script: vendor/bin/php-cs-fixer fix --dry-run -v --show-progress=dots --diff-format=udiff
    - stage: PHPCPD
      env: phpcpd
      install:
        - wget https://phar.phpunit.de/phpcpd.phar
        - chmod +x phpcpd.phar
        - travis_retry composer install
      script: ./phpcpd.phar app
